
export class CssSpec {
    public static readonly INHERITED_PROPS = [
        'azimuth',
        'border-collapse',
        'border-spacing',
        'caption-side',
        'color',
        'cursor',
        'direction',
        'elevation',
        'empty-cells',
        'font-family',
        'font-size',
        'font-style',
        'font-variant',
        'font-weight',
        'font',
        'letter-spacing',
        'line-height',
        'list-style-image',
        'list-style-position',
        'list-style-type',
        'list-style',
        'orphans',
        'pitch-range',
        'pitch',
        'quotes',
        'richness',
        'speak-header',
        'speak-numeral',
        'speak-punctuation',
        'speak',
        'speech-rate',
        'stress',
        'text-align',
        'text-indent',
        'text-transform',
        'visibility',
        'voice-family',
        'volume',
        'white-space',
        'widows',
        'word-spacing'
    ];

    // https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties
    public static readonly SHORTHAND_PROPS = [
        'background',
        'border',
        'border-bottom',
        'border-color',
        'border-left',
        'border-radius',
        'border-right',
        'border-style',
        'border-top',
        'border-width',
        'font',
        'list-style',
        'margin',
        'offset',
        'outline',
        'overflow',
        'padding',
        'text-decoration'
    ];

    public static readonly INITIAL_VALUES = {
        "background-attachment": [{"type": "keyword", "value": "scroll"}],
        "background-color": [{"type": "color", "value": "transparent"}],
        "background-image": [{"type": "keyword", "value": "none"}],
        "background-position": [{"type": "unit", "value": 0, "unit": "%"}, {"type": "unit", "value": 0, "unit": "%"}],
        "background-repeat": [{"type": "keyword", "value": "repeat"}],
        "background": [{"type": "color", "value": "transparent"}],
        "border-collapse": [{"type": "keyword", "value": "separate"}],
        "border-color": [{"type": "color", "value": "black"}],
        "border-spacing": [{"type": "unit", "value": 0, "unit": ""}],
        "border-style": [{"type": "keyword", "value": "solid"}],
        "border-top-color": [{"type": "color", "value": "black"}],
        "border-right-color": [{"type": "color", "value": "black"}],
        "border-bottom-color": [{"type": "color", "value": "black"}],
        "border-left-color": [{"type": "color", "value": "black"}],
        "border-top-style": [{"type": "keyword", "value": "none"}],
        "border-right-style": [{"type": "keyword", "value": "none"}],
        "border-bottom-style": [{"type": "keyword", "value": "none"}],
        "border-left-style": [{"type": "keyword", "value": "none"}],
        "border-top-width": [{"type": "unit", "value": 0, "unit": ""}],
        "border-right-width": [{"type": "unit", "value": 0, "unit": ""}],
        "border-bottom-width": [{"type": "unit", "value": 0, "unit": ""}],
        "border-left-width": [{"type": "unit", "value": 0, "unit": ""}],
        "border-top": [{"type": "unit", "value": 0, "unit": ""}, {"type": "keyword", "value": "none"}, {"type": "color", "value": "black"}],
        "border-right": [{"type": "unit", "value": 0, "unit": ""}, {"type": "keyword", "value": "none"}, {"type": "color", "value": "black"}],
        "border-bottom": [{"type": "unit", "value": 0, "unit": ""}, {"type": "keyword", "value": "none"}, {"type": "color", "value": "black"}],
        "border-left": [{"type": "unit", "value": 0, "unit": ""}, {"type": "keyword", "value": "none"}, {"type": "color", "value": "black"}],
        "border-width": [{"type": "unit", "value": 0, "unit": ""}],
        "border": [{"type": "keyword", "value": "none"}],
        "bottom": [{"type": "keyword", "value": "auto"}],
        "caption-side": [{"type": "keyword", "value": "top"}],
        "clear": [{"type": "keyword", "value": "none"}],
        "clip": [{"type": "keyword", "value": "auto"}],
        "color": [{"type": "color", "value": "black"}],
        "content": [{"type": "keyword", "value": "normal"}],
        "counter-increment": [{"type": "keyword", "value": "none"}],
        "counter-reset": [{"type": "keyword", "value": "none"}],
        "cursor": [{"type": "keyword", "value": "auto"}],
        "direction": [{"type": "keyword", "value": "ltr"}],
        "display": [{"type": "keyword", "value": "inline"}],
        "empty-cells": [{"type": "keyword", "value": "show"}],
        "float": [{"type": "keyword", "value": "none"}],
        "font-family": [{"type": "keyword", "value": "Times"}],
        "font-size": [{"type": "unit", "value": 16, "unit": "px"}],
        "font-style": [{"type": "keyword", "value": "normal"}],
        "font-variant": [{"type": "keyword", "value": "normal"}],
        "font-weight": [{"type": "keyword", "value": "normal"}],
        "font": [{"type": "unit", "value": 16, "unit": "px"}, {"type": "keyword", "value": "Times"}],
        "height": [{"type": "keyword", "value": "auto"}],
        "left": [{"type": "keyword", "value": "auto"}],
        "letter-spacing": [{"type": "keyword", "value": "normal"}],
        "line-height": [{"type": "keyword", "value": "normal"}],
        "list-style-image": [{"type": "keyword", "value": "none"}],
        "list-style-position": [{"type": "keyword", "value": "outside"}],
        "list-style-type": [{"type": "keyword", "value": "disc"}],
        "list-style": [{"type": "keyword", "value": "disc"}, {"type": "keyword", "value": "outside"}, {"type": "keyword", "value": "none"}],
        "margin-right": [{"type": "unit", "value": 0, "unit": ""}],
        "margin-left": [{"type": "unit", "value": 0, "unit": ""}],
        "margin-top": [{"type": "unit", "value": 0, "unit": ""}],
        "margin-bottom": [{"type": "unit", "value": 0, "unit": ""}],
        "margin": [{"type": "unit", "value": 0, "unit": ""}],
        "max-height": [{"type": "keyword", "value": "none"}],
        "max-width": [{"type": "keyword", "value": "none"}],
        "min-height": [{"type": "unit", "value": 0, "unit": ""}],
        "min-width": [{"type": "unit", "value": 0, "unit": ""}],
        "orphans": [{"type": "unit", "value": 2, "unit": ""}],
        "outline-color": [{"type": "keyword", "value": "invert"}],
        "outline-style": [{"type": "keyword", "value": "none"}],
        "outline-width": [{"type": "unit", "value": 0, "unit": ""}],
        "outline": [{"type": "unit", "value": 0, "unit": ""}, {"type": "keyword", "value": "invert"}, {"type": "keyword", "value": "none"}],
        "overflow": [{"type": "keyword", "value": "visible"}],
        "padding-top": [{"type": "unit", "value": 0, "unit": ""}],
        "padding-right": [{"type": "unit", "value": 0, "unit": ""}],
        "padding-bottom": [{"type": "unit", "value": 0, "unit": ""}],
        "padding-left": [{"type": "unit", "value": 0, "unit": ""}],
        "padding": [{"type": "unit", "value": 0, "unit": ""}],
        "page-break-after": [{"type": "keyword", "value": "auto"}],
        "page-break-before": [{"type": "keyword", "value": "auto"}],
        "page-break-inside": [{"type": "keyword", "value": "auto"}],
        "position": [{"type": "keyword", "value": "static"}],
        "quotes": [{"type": "keyword", "value": "none"}],
        "right": [{"type": "keyword", "value": "auto"}],
        "table-layout": [{"type": "keyword", "value": "auto"}],
        "text-align": [{"type": "keyword", "value": "left"}],
        "text-decoration": [{"type": "keyword", "value": "none"}],
        "text-indent": [{"type": "unit", "value": 0, "unit": ""}],
        "text-transform": [{"type": "keyword", "value": "none"}],
        "top": [{"type": "keyword", "value": "auto"}],
        "unicode-bidi": [{"type": "keyword", "value": "normal"}],
        "vertical-align": [{"type": "keyword", "value": "baseline"}],
        "visibility": [{"type": "keyword", "value": "visible"}],
        "white-space": [{"type": "keyword", "value": "normal"}],
        "widows": [{"type": "unit", "value": 2, "unit": ""}],
        "width": [{"type": "keyword", "value": "auto"}],
        "word-spacing": [{"type": "keyword", "value": "normal"}],
        "z-index": [{"type": "keyword", "value": "auto"}]
    };

    public static readonly COLOR_NAMES = {
        'aliceblue': '#F0F8FF',
        'antiquewhite': '#FAEBD7',
        'aqua': '#00FFFF',
        'aquamarine': '#7FFFD4',
        'azure': '#F0FFFF',
        'beige': '#F5F5DC',
        'bisque': '#FFE4C4',
        'black': '#000000',
        'blanchedalmond': '#FFEBCD',
        'blue': '#0000FF',
        'blueviolet': '#8A2BE2',
        'brown': '#A52A2A',
        'burlywood': '#DEB887',
        'cadetblue': '#5F9EA0',
        'chartreuse': '#7FFF00',
        'chocolate': '#D2691E',
        'coral': '#FF7F50',
        'cornflowerblue': '#6495ED',
        'cornsilk': '#FFF8DC',
        'crimson': '#DC143C',
        'cyan': '#00FFFF',
        'darkblue': '#00008B',
        'darkcyan': '#008B8B',
        'darkgoldenrod': '#B8860B',
        'darkgray': '#A9A9A9',
        'darkgrey': '#A9A9A9',
        'darkgreen': '#006400',
        'darkkhaki': '#BDB76B',
        'darkmagenta': '#8B008B',
        'darkolivegreen': '#556B2F',
        'darkorange': '#FF8C00',
        'darkorchid': '#9932CC',
        'darkred': '#8B0000',
        'darksalmon': '#E9967A',
        'darkseagreen': '#8FBC8F',
        'darkslateblue': '#483D8B',
        'darkslategray': '#2F4F4F',
        'darkslategrey': '#2F4F4F',
        'darkturquoise': '#00CED1',
        'darkviolet': '#9400D3',
        'deeppink': '#FF1493',
        'deepskyblue': '#00BFFF',
        'dimgray': '#696969',
        'dimgrey': '#696969',
        'dodgerblue': '#1E90FF',
        'firebrick': '#B22222',
        'floralwhite': '#FFFAF0',
        'forestgreen': '#228B22',
        'fuchsia': '#FF00FF',
        'gainsboro': '#DCDCDC',
        'ghostwhite': '#F8F8FF',
        'gold': '#FFD700',
        'goldenrod': '#DAA520',
        'gray': '#808080',
        'grey': '#808080',
        'green': '#008000',
        'greenyellow': '#ADFF2F',
        'honeydew': '#F0FFF0',
        'hotpink': '#FF69B4',
        'indianred': '#CD5C5C',
        'indigo': '#4B0082',
        'ivory': '#FFFFF0',
        'khaki': '#F0E68C',
        'lavender': '#E6E6FA',
        'lavenderblush': '#FFF0F5',
        'lawngreen': '#7CFC00',
        'lemonchiffon': '#FFFACD',
        'lightblue': '#ADD8E6',
        'lightcoral': '#F08080',
        'lightcyan': '#E0FFFF',
        'lightgoldenrodyellow': '#FAFAD2',
        'lightgray': '#D3D3D3',
        'lightgrey': '#D3D3D3',
        'lightgreen': '#90EE90',
        'lightpink': '#FFB6C1',
        'lightsalmon': '#FFA07A',
        'lightseagreen': '#20B2AA',
        'lightskyblue': '#87CEFA',
        'lightslategray': '#778899',
        'lightslategrey': '#778899',
        'lightsteelblue': '#B0C4DE',
        'lightyellow': '#FFFFE0',
        'lime': '#00FF00',
        'limegreen': '#32CD32',
        'linen': '#FAF0E6',
        'magenta': '#FF00FF',
        'maroon': '#800000',
        'mediumaquamarine': '#66CDAA',
        'mediumblue': '#0000CD',
        'mediumorchid': '#BA55D3',
        'mediumpurple': '#9370DB',
        'mediumseagreen': '#3CB371',
        'mediumslateblue': '#7B68EE',
        'mediumspringgreen': '#00FA9A',
        'mediumturquoise': '#48D1CC',
        'mediumvioletred': '#C71585',
        'midnightblue': '#191970',
        'mintcream': '#F5FFFA',
        'mistyrose': '#FFE4E1',
        'moccasin': '#FFE4B5',
        'navajowhite': '#FFDEAD',
        'navy': '#000080',
        'oldlace': '#FDF5E6',
        'olive': '#808000',
        'olivedrab': '#6B8E23',
        'orange': '#FFA500',
        'orangered': '#FF4500',
        'orchid': '#DA70D6',
        'palegoldenrod': '#EEE8AA',
        'palegreen': '#98FB98',
        'paleturquoise': '#AFEEEE',
        'palevioletred': '#DB7093',
        'papayawhip': '#FFEFD5',
        'peachpuff': '#FFDAB9',
        'peru': '#CD853F',
        'pink': '#FFC0CB',
        'plum': '#DDA0DD',
        'powderblue': '#B0E0E6',
        'purple': '#800080',
        'rebeccapurple': '#663399',
        'red': '#FF0000',
        'rosybrown': '#BC8F8F',
        'royalblue': '#4169E1',
        'saddlebrown': '#8B4513',
        'salmon': '#FA8072',
        'sandybrown': '#F4A460',
        'seagreen': '#2E8B57',
        'seashell': '#FFF5EE',
        'sienna': '#A0522D',
        'silver': '#C0C0C0',
        'skyblue': '#87CEEB',
        'slateblue': '#6A5ACD',
        'slategray': '#708090',
        'slategrey': '#708090',
        'snow': '#FFFAFA',
        'springgreen': '#00FF7F',
        'steelblue': '#4682B4',
        'tan': '#D2B48C',
        'teal': '#008080',
        'thistle': '#D8BFD8',
        'tomato': '#FF6347',
        'turquoise': '#40E0D0',
        'violet': '#EE82EE',
        'wheat': '#F5DEB3',
        'white': '#FFFFFF',
        'whitesmoke': '#F5F5F5',
        'yellow': '#FFFF00',
        'yellowgreen': '#9ACD32',
        'transparent': 'transparent'
    }

    // normal values (browser dependent)
    // line-height: normal = 1.15

}
