
export class CssSpec {
    public static readonly INHERITED_PROPS = [
        'azimuth',
        'border-collapse',
        'border-spacing',
        'caption-side',
        'color',
        'cursor',
        'direction',
        'elevation',
        'empty-cells',
        'font-family',
        'font-size',
        'font-style',
        'font-variant',
        'font-weight',
        'font',
        'letter-spacing',
        'line-height',
        'list-style-image',
        'list-style-position',
        'list-style-type',
        'list-style',
        'orphans',
        'pitch-range',
        'pitch',
        'quotes',
        'richness',
        'speak-header',
        'speak-numeral',
        'speak-punctuation',
        'speak',
        'speech-rate',
        'stress',
        'text-align',
        'text-indent',
        'text-transform',
        'visibility',
        'voice-family',
        'volume',
        'white-space',
        'widows',
        'word-spacing'
    ];

    public static readonly INITIAL_VALUES = {
        "background-attachment": [{"type": "keyword", "value": "scroll"}],
        "background-color": [{"type": "keyword", "value": "transparent"}],
        "background-image": [{"type": "keyword", "value": "none"}],
        "background-position": [{"type": "unit", "value": 0, "unit": "%"}, {"type": "unit", "value": 0, "unit": "%"}],
        "background-repeat": [{"type": "keyword", "value": "repeat"}],
        "background": [{"type": "keyword", "value": "transparent"}],
        "border-collapse": [{"type": "keyword", "value": "separate"}],
        "border-color": [{"type": "keyword", "value": "black"}],
        "border-spacing": [{"type": "unit", "value": 0, "unit": ""}],
        "border-style": [{"type": "keyword", "value": "solid"}],
        "border-top-color": [{"type": "keyword", "value": "black"}],
        "border-right-color": [{"type": "keyword", "value": "black"}],
        "border-bottom-color": [{"type": "keyword", "value": "black"}],
        "border-left-color": [{"type": "keyword", "value": "black"}],
        "border-top-style": [{"type": "keyword", "value": "none"}],
        "border-right-style": [{"type": "keyword", "value": "none"}],
        "border-bottom-style": [{"type": "keyword", "value": "none"}],
        "border-left-style": [{"type": "keyword", "value": "none"}],
        "border-top-width": [{"type": "keyword", "value": "medium"}],
        "border-right-width": [{"type": "keyword", "value": "medium"}],
        "border-bottom-width": [{"type": "keyword", "value": "medium"}],
        "border-left-width": [{"type": "keyword", "value": "medium"}],
        "border-top": [{"type": "keyword", "value": "medium"}, {"type": "keyword", "value": "none"}, {"type": "keyword", "value": "black"}],
        "border-right": [{"type": "keyword", "value": "medium"}, {"type": "keyword", "value": "none"}, {"type": "keyword", "value": "black"}],
        "border-bottom": [{"type": "keyword", "value": "medium"}, {"type": "keyword", "value": "none"}, {"type": "keyword", "value": "black"}],
        "border-left": [{"type": "keyword", "value": "medium"}, {"type": "keyword", "value": "none"}, {"type": "keyword", "value": "black"}],
        "border-width": [{"type": "unit", "value": 0, "unit": ""}],
        "border": [{"type": "keyword", "value": "none"}],
        "bottom": [{"type": "keyword", "value": "auto"}],
        "caption-side": [{"type": "keyword", "value": "top"}],
        "clear": [{"type": "keyword", "value": "none"}],
        "clip": [{"type": "keyword", "value": "auto"}],
        "color": [{"type": "keyword", "value": "black"}],
        "content": [{"type": "keyword", "value": "normal"}],
        "counter-increment": [{"type": "keyword", "value": "none"}],
        "counter-reset": [{"type": "keyword", "value": "none"}],
        "cursor": [{"type": "keyword", "value": "auto"}],
        "direction": [{"type": "keyword", "value": "ltr"}],
        "display": [{"type": "keyword", "value": "inline"}],
        "empty-cells": [{"type": "keyword", "value": "show"}],
        "float": [{"type": "keyword", "value": "none"}],
        "font-family": [{"type": "keyword", "value": "Times"}],
        "font-size": [{"type": "keyword", "value": "medium"}],
        "font-style": [{"type": "keyword", "value": "normal"}],
        "font-variant": [{"type": "keyword", "value": "normal"}],
        "font-weight": [{"type": "keyword", "value": "normal"}],
        "font": [{"type": "keyword", "value": "medium"}, {"type": "keyword", "value": "Times"}],
        "height": [{"type": "keyword", "value": "auto"}],
        "left": [{"type": "keyword", "value": "auto"}],
        "letter-spacing": [{"type": "keyword", "value": "normal"}],
        "line-height": [{"type": "keyword", "value": "normal"}],
        "list-style-image": [{"type": "keyword", "value": "none"}],
        "list-style-position": [{"type": "keyword", "value": "outside"}],
        "list-style-type": [{"type": "keyword", "value": "disc"}],
        "list-style": [{"type": "keyword", "value": "disc"}, {"type": "keyword", "value": "outside"}, {"type": "keyword", "value": "none"}],
        "margin-right": [{"type": "unit", "value": 0, "unit": ""}],
        "margin-left": [{"type": "unit", "value": 0, "unit": ""}],
        "margin-top": [{"type": "unit", "value": 0, "unit": ""}],
        "margin-bottom": [{"type": "unit", "value": 0, "unit": ""}],
        "margin": [{"type": "unit", "value": 0, "unit": ""}],
        "max-height": [{"type": "keyword", "value": "none"}],
        "max-width": [{"type": "keyword", "value": "none"}],
        "min-height": [{"type": "unit", "value": 0, "unit": ""}],
        "min-width": [{"type": "unit", "value": 0, "unit": ""}],
        "orphans": [{"type": "unit", "value": 2, "unit": ""}],
        "outline-color": [{"type": "keyword", "value": "invert"}],
        "outline-style": [{"type": "keyword", "value": "none"}],
        "outline-width": [{"type": "keyword", "value": "medium"}],
        "outline": [{"type": "keyword", "value": "medium"}, {"type": "keyword", "value": "invert"}, {"type": "keyword", "value": "none"}],
        "overflow": [{"type": "keyword", "value": "visible"}],
        "padding-top": [{"type": "unit", "value": 0, "unit": ""}],
        "padding-right": [{"type": "unit", "value": 0, "unit": ""}],
        "padding-bottom": [{"type": "unit", "value": 0, "unit": ""}],
        "padding-left": [{"type": "unit", "value": 0, "unit": ""}],
        "padding": [{"type": "unit", "value": 0, "unit": ""}],
        "page-break-after": [{"type": "keyword", "value": "auto"}],
        "page-break-before": [{"type": "keyword", "value": "auto"}],
        "page-break-inside": [{"type": "keyword", "value": "auto"}],
        "position": [{"type": "keyword", "value": "static"}],
        "quotes": [{"type": "keyword", "value": "none"}],
        "right": [{"type": "keyword", "value": "auto"}],
        "table-layout": [{"type": "keyword", "value": "auto"}],
        "text-align": [{"type": "keyword", "value": "left"}],
        "text-decoration": [{"type": "keyword", "value": "none"}],
        "text-indent": [{"type": "unit", "value": 0, "unit": ""}],
        "text-transform": [{"type": "keyword", "value": "none"}],
        "top": [{"type": "keyword", "value": "auto"}],
        "unicode-bidi": [{"type": "keyword", "value": "normal"}],
        "vertical-align": [{"type": "keyword", "value": "baseline"}],
        "visibility": [{"type": "keyword", "value": "visible"}],
        "white-space": [{"type": "keyword", "value": "normal"}],
        "widows": [{"type": "unit", "value": 2, "unit": ""}],
        "width": [{"type": "keyword", "value": "auto"}],
        "word-spacing": [{"type": "keyword", "value": "normal"}],
        "z-index": [{"type": "keyword", "value": "auto"}]
    }
}
