export class CssSpec {
}
CssSpec.INHERITED_PROPS = [
    'azimuth',
    'border-collapse',
    'border-spacing',
    'caption-side',
    'color',
    'cursor',
    'direction',
    'elevation',
    'empty-cells',
    'font-family',
    'font-size',
    'font-style',
    'font-variant',
    'font-weight',
    'font',
    'letter-spacing',
    'line-height',
    'list-style-image',
    'list-style-position',
    'list-style-type',
    'list-style',
    'orphans',
    'pitch-range',
    'pitch',
    'quotes',
    'richness',
    'speak-header',
    'speak-numeral',
    'speak-punctuation',
    'speak',
    'speech-rate',
    'stress',
    'text-align',
    'text-indent',
    'text-transform',
    'visibility',
    'voice-family',
    'volume',
    'white-space',
    'widows',
    'word-spacing'
];
CssSpec.INITIAL_VALUES = {
    'background-attachment': 'scroll',
    'background-color': 'transparent',
    'background-image': 'none',
    'background-position': '0% 0%',
    'background-repeat': 'repeat',
    'background': 'transparent',
    'border-collapse': 'separate',
    'border-color': 'black',
    'border-spacing': '0',
    'border-style': 'solid',
    'border-top-color': 'black',
    'border-right-color': 'black',
    'border-bottom-color': 'black',
    'border-left-color': 'black',
    'border-top-style': 'none',
    'border-right-style': 'none',
    'border-bottom-style': 'none',
    'border-left-style': 'none',
    'border-top-width': 'medium',
    'border-right-width': 'medium',
    'border-bottom-width': 'medium',
    'border-left-width': 'medium',
    'border-top': 'medium none black',
    'border-right': 'medium none black',
    'border-bottom': 'medium none black',
    'border-left': 'medium none black',
    'border-width': '0',
    'border': 'none',
    'bottom': 'auto',
    'caption-side': 'top',
    'clear': 'none',
    'clip': 'auto',
    'color': 'black',
    'content': 'normal',
    'counter-increment': 'none',
    'counter-reset': 'none',
    'cursor': 'auto',
    'direction': 'ltr',
    'display': 'inline',
    'empty-cells': 'show',
    'float': 'none',
    'font-family': 'Times',
    'font-size': 'medium',
    'font-style': 'normal',
    'font-variant': 'normal',
    'font-weight': 'normal',
    'font': 'medium Times',
    'height': 'auto',
    'left': 'auto',
    'letter-spacing': 'normal',
    'line-height': 'normal',
    'list-style-image': 'none',
    'list-style-position': 'outside',
    'list-style-type': 'disc',
    'list-style': 'disc outside none',
    'margin-right': '0',
    'margin-left': '0',
    'margin-top': '0',
    'margin-bottom': '0',
    'margin': '0',
    'max-height': 'none',
    'max-width': 'none',
    'min-height': '0',
    'min-width': '0',
    'orphans': '2',
    'outline-color': 'invert',
    'outline-style': 'none',
    'outline-width': 'medium',
    'outline': 'medium invert none',
    'overflow': 'visible',
    'padding-top': '0',
    'padding-right': '0',
    'padding-bottom': '0',
    'padding-left': '0',
    'padding': '0',
    'page-break-after': 'auto',
    'page-break-before': 'auto',
    'page-break-inside': 'auto',
    'position': 'static',
    'quotes': 'none',
    'right': 'auto',
    'table-layout': 'auto',
    'text-align': 'left',
    'text-decoration': 'none',
    'text-indent': '0',
    'text-transform': 'none',
    'top': 'auto',
    'unicode-bidi': 'normal',
    'vertical-align': 'baseline',
    'visibility': 'visible',
    'white-space': 'normal',
    'widows': '2',
    'width': 'auto',
    'word-spacing': 'normal',
    'z-index': 'auto',
};
